# Generated by Django 3.2.9 on 2021-12-28 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20211211_2220'),
        ('students', '0004_auto_20211218_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='groups.group'),
        ),
    ]
