# Generated by Django 3.2.9 on 2021-12-04 23:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('num_of_courses', models.IntegerField()),
                ('employment_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
