# Generated by Django 3.2.9 on 2021-12-31 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='num_of_courses',
            field=models.IntegerField(null=True),
        ),
    ]
