# Generated by Django 3.2.9 on 2021-12-04 23:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('group_size', models.IntegerField()),
                ('start_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
