# Generated by Django 3.2.9 on 2021-12-31 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_teacher_num_of_courses'),
        ('groups', '0002_group_headman'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='teachers_gr',
            field=models.ManyToManyField(related_name='groups', to='teachers.Teacher'),
        ),
    ]
